#include "IncidentTimeline.h"
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QSqlQuery>
#include <QSqlError>
#include <QPushButton>
#include <QFileDialog>
#include <QTextStream>
#include <QTimer>
#include <QMessageBox>

IncidentTimeline::IncidentTimeline(QWidget *parent) : QWidget(parent) {
    auto *layout = new QVBoxLayout(this);

    QLabel *title = new QLabel("Unified Incident Timeline");
    title->setStyleSheet("color: #00bcd4; font: bold 16pt; margin: 10px;");
    layout->addWidget(title);

    timelineBox = new QTextEdit();
    timelineBox->setReadOnly(true);
    timelineBox->setStyleSheet("background-color: #1e1e1e; color: #ffffff; font-family: 'Consolas', monospace;");
    layout->addWidget(timelineBox);

    auto *buttonLayout = new QHBoxLayout();
    QPushButton *refreshBtn = new QPushButton("Refresh Timeline");
    QPushButton *csvBtn = new QPushButton("Export to CSV");
    QPushButton *clearBtn = new QPushButton("Clear Timeline");
    
    refreshBtn->setStyleSheet("QPushButton { background-color: #2196f3; color: white; padding: 8px; border-radius: 4px; }");
    csvBtn->setStyleSheet("QPushButton { background-color: #4caf50; color: white; padding: 8px; border-radius: 4px; }");
    clearBtn->setStyleSheet("QPushButton { background-color: #f44336; color: white; padding: 8px; border-radius: 4px; }");
    
    buttonLayout->addWidget(refreshBtn);
    buttonLayout->addWidget(csvBtn);
    buttonLayout->addWidget(clearBtn);
    layout->addLayout(buttonLayout);

    connect(refreshBtn, &QPushButton::clicked, this, &IncidentTimeline::refreshTimeline);
    connect(csvBtn, &QPushButton::clicked, this, &IncidentTimeline::exportCSV);
    connect(clearBtn, &QPushButton::clicked, [this]() { timelineBox->clear(); });

    // Initialize database connection
    db = QSqlDatabase::addDatabase("QSQLITE", "timeline");
    db.setDatabaseName("cyberrecon_main.db");
    if (!db.open()) {
        QMessageBox::warning(this, "Database Error", "Could not open timeline database");
    }

    // Auto-refresh timer
    QTimer *timer = new QTimer(this);
    connect(timer, &QTimer::timeout, this, &IncidentTimeline::refreshTimeline);
    timer->start(5000); // every 5 seconds

    refreshTimeline();
}

void IncidentTimeline::exportCSV() {
    QString filename = QFileDialog::getSaveFileName(this, "Export Timeline CSV", "", "CSV Files (*.csv)");
    if(filename.isEmpty()) return;

    QFile file(filename);
    if(file.open(QIODevice::WriteOnly)) {
        QTextStream out(&file);
        out << "Timestamp,Panel,Severity,Message\n";

        QSqlQuery q("SELECT timestamp, panel, severity, message FROM events ORDER BY timestamp DESC", db);
        while(q.next()) {
            QString ts = q.value(0).toString();
            QString panel = q.value(1).toString();
            QString sev = q.value(2).toString();
            QString msg = q.value(3).toString();

            QString icon = (sev=="Critical") ? "🔴" : (sev=="Warning") ? "🟠" : "🟢";
            out << ts << "," << panel << "," << icon << " " << sev << ",\"" << msg << "\"\n";
        }
        
        QMessageBox::information(this, "Export Complete", "Timeline exported to " + filename);
    }
}

void IncidentTimeline::refreshTimeline() {
    timelineBox->clear();

    QSqlQuery q("SELECT timestamp, panel, severity, message FROM events ORDER BY timestamp DESC LIMIT 50", db);
    while(q.next()) {
        QString ts = q.value(0).toString();
        QString panel = q.value(1).toString();
        QString sev = q.value(2).toString();
        QString msg = q.value(3).toString();

        QString color = "#4caf50"; // default Info (green)
        QString icon = "🟢";
        if(sev == "Warning") {
            color = "#ff9800";
            icon = "🟠";
        } else if(sev == "Critical") {
            color = "#f44336";
            icon = "🔴";
        }

        QString line = QString("<font color='%1'>[%2] %3 %4 - %5</font>")
                       .arg(color).arg(ts).arg(icon).arg(panel).arg(msg);

        timelineBox->append(line);
    }
    
    if (timelineBox->toPlainText().isEmpty()) {
        timelineBox->append("<font color='#607d8b'>[Info] No events in timeline. Events will appear as they are generated by other modules.</font>");
    }
}