#include "ReportGenerator.h"
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QPushButton>
#include <QFileDialog>
#include <QTextStream>
#include <QLabel>
#include <QComboBox>
#include <QTextEdit>
#include <QMessageBox>
#include <QSqlQuery>
#include <QDateTime>

ReportGenerator::ReportGenerator(QWidget *parent) : QWidget(parent) {
    auto *layout = new QVBoxLayout(this);

    QLabel *title = new QLabel("Security Report Generator");
    title->setStyleSheet("color: #00bcd4; font: bold 16pt; margin: 10px;");
    layout->addWidget(title);

    // Report type selection
    auto *typeLayout = new QHBoxLayout();
    typeLayout->addWidget(new QLabel("Report Type:"));
    
    reportTypeCombo = new QComboBox();
    reportTypeCombo->addItem("Incident Summary Report");
    reportTypeCombo->addItem("Threat Intelligence Report");
    reportTypeCombo->addItem("Compliance Audit Report");
    reportTypeCombo->addItem("Forensics Analysis Report");
    reportTypeCombo->addItem("Executive Dashboard Report");
    reportTypeCombo->setStyleSheet("padding: 5px; font-size: 11pt;");
    
    typeLayout->addWidget(reportTypeCombo);
    typeLayout->addStretch();
    layout->addLayout(typeLayout);

    // Report preview
    reportPreview = new QTextEdit();
    reportPreview->setReadOnly(true);
    reportPreview->setStyleSheet("background-color: #2b2b2b; color: #ffffff; font-family: 'Consolas', monospace; padding: 10px;");
    layout->addWidget(reportPreview);

    // Buttons
    auto *buttonLayout = new QHBoxLayout();
    QPushButton *generateBtn = new QPushButton("Generate Report");
    QPushButton *exportTxtBtn = new QPushButton("Export as TXT");
    QPushButton *exportCsvBtn = new QPushButton("Export as CSV");
    QPushButton *clearBtn = new QPushButton("Clear");

    generateBtn->setStyleSheet("QPushButton { background-color: #2196f3; color: white; padding: 8px; border-radius: 4px; }");
    exportTxtBtn->setStyleSheet("QPushButton { background-color: #4caf50; color: white; padding: 8px; border-radius: 4px; }");
    exportCsvBtn->setStyleSheet("QPushButton { background-color: #ff9800; color: white; padding: 8px; border-radius: 4px; }");
    clearBtn->setStyleSheet("QPushButton { background-color: #607d8b; color: white; padding: 8px; border-radius: 4px; }");

    buttonLayout->addWidget(generateBtn);
    buttonLayout->addWidget(exportTxtBtn);
    buttonLayout->addWidget(exportCsvBtn);
    buttonLayout->addWidget(clearBtn);
    buttonLayout->addStretch();
    layout->addLayout(buttonLayout);

    connect(generateBtn, &QPushButton::clicked, this, &ReportGenerator::generateReport);
    connect(exportTxtBtn, &QPushButton::clicked, this, &ReportGenerator::exportTxt);
    connect(exportCsvBtn, &QPushButton::clicked, this, &ReportGenerator::exportCsv);
    connect(clearBtn, &QPushButton::clicked, [this]() { reportPreview->clear(); });

    // Generate initial report
    generateReport();
}

void ReportGenerator::generateReport() {
    QString reportType = reportTypeCombo->currentText();
    QString report;
    
    QString timestamp = QDateTime::currentDateTime().toString("yyyy-MM-dd hh:mm:ss");
    
    report += "=====================================\n";
    report += "CyberRecon Suite v1.7\n";
    report += reportType + "\n";
    report += "Generated: " + timestamp + "\n";
    report += "=====================================\n\n";

    if (reportType == "Incident Summary Report") {
        report += generateIncidentSummary();
    } else if (reportType == "Threat Intelligence Report") {
        report += generateThreatIntelReport();
    } else if (reportType == "Compliance Audit Report") {
        report += generateComplianceReport();
    } else if (reportType == "Forensics Analysis Report") {
        report += generateForensicsReport();
    } else if (reportType == "Executive Dashboard Report") {
        report += generateExecutiveReport();
    }

    report += "\n=====================================\n";
    report += "Report generated by CyberRecon Suite\n";
    report += "For questions, contact: security@company.com\n";
    report += "=====================================\n";

    reportPreview->setPlainText(report);
    
    // Log report generation
    QSqlQuery q;
    q.prepare("INSERT INTO events (panel, severity, message) VALUES ('Reports', 'Info', :msg)");
    q.bindValue(":msg", QString("Generated %1").arg(reportType));
    q.exec();
}

void ReportGenerator::exportTxt() {
    QString fileName = QFileDialog::getSaveFileName(this, "Save Report", 
                                                   QString("CyberRecon_Report_%1.txt")
                                                   .arg(QDateTime::currentDateTime().toString("yyyyMMdd_hhmmss")), 
                                                   "Text Files (*.txt)");
    if (fileName.isEmpty()) return;

    QFile file(fileName);
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream out(&file);
        out << reportPreview->toPlainText();
        file.close();
        QMessageBox::information(this, "Export Complete", "Report exported to " + fileName);
    } else {
        QMessageBox::warning(this, "Export Failed", "Could not save file: " + fileName);
    }
}

void ReportGenerator::exportCsv() {
    QString fileName = QFileDialog::getSaveFileName(this, "Save Report as CSV", 
                                                   QString("CyberRecon_Data_%1.csv")
                                                   .arg(QDateTime::currentDateTime().toString("yyyyMMdd_hhmmss")), 
                                                   "CSV Files (*.csv)");
    if (fileName.isEmpty()) return;

    QFile file(fileName);
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream out(&file);
        out << "Timestamp,Panel,Severity,Message\n";
        
        // Export recent events as CSV
        QSqlQuery q("SELECT timestamp, panel, severity, message FROM events ORDER BY timestamp DESC LIMIT 100");
        while (q.next()) {
            out << q.value(0).toString() << ","
                << q.value(1).toString() << ","
                << q.value(2).toString() << ",\""
                << q.value(3).toString() << "\"\n";
        }
        
        file.close();
        QMessageBox::information(this, "Export Complete", "Data exported to " + fileName);
    } else {
        QMessageBox::warning(this, "Export Failed", "Could not save file: " + fileName);
    }
}

QString ReportGenerator::generateIncidentSummary() {
    QString summary;
    summary += "INCIDENT SUMMARY\n";
    summary += "================\n\n";
    
    // Query recent critical events
    QSqlQuery q("SELECT COUNT(*) FROM events WHERE severity='Critical'");
    int criticalCount = 0;
    if (q.exec() && q.next()) {
        criticalCount = q.value(0).toInt();
    }
    
    QSqlQuery q2("SELECT COUNT(*) FROM events WHERE severity='Warning'");
    int warningCount = 0;
    if (q2.exec() && q2.next()) {
        warningCount = q2.value(0).toInt();
    }
    
    summary += QString("Critical Incidents: %1\n").arg(criticalCount);
    summary += QString("Warning Events: %1\n").arg(warningCount);
    summary += "\nRecent Critical Events:\n";
    summary += "-----------------------\n";
    
    QSqlQuery q3("SELECT timestamp, panel, message FROM events WHERE severity='Critical' ORDER BY timestamp DESC LIMIT 5");
    while (q3.next()) {
        summary += QString("[%1] %2: %3\n")
                  .arg(q3.value(0).toString())
                  .arg(q3.value(1).toString())
                  .arg(q3.value(2).toString());
    }
    
    return summary;
}

QString ReportGenerator::generateThreatIntelReport() {
    QString report;
    report += "THREAT INTELLIGENCE REPORT\n";
    report += "==========================\n\n";
    report += "IOC Analysis:\n";
    report += "- 15 new malicious IPs identified\n";
    report += "- 8 suspicious domains blocked\n";
    report += "- 3 malware families detected\n\n";
    report += "Threat Landscape:\n";
    report += "- Increased phishing campaigns targeting finance sector\n";
    report += "- New ransomware variant observed in the wild\n";
    report += "- APT group activity detected in region\n\n";
    return report;
}

QString ReportGenerator::generateComplianceReport() {
    QString report;
    report += "COMPLIANCE AUDIT REPORT\n";
    report += "=======================\n\n";
    report += "NIST Framework Compliance: 85%\n";
    report += "GDPR Compliance: 92%\n";
    report += "HIPAA Compliance: 88%\n\n";
    report += "Areas for Improvement:\n";
    report += "- Access control documentation\n";
    report += "- Incident response procedures\n";
    report += "- Data retention policies\n\n";
    return report;
}

QString ReportGenerator::generateForensicsReport() {
    QString report;
    report += "FORENSICS ANALYSIS REPORT\n";
    report += "=========================\n\n";
    report += "Evidence Collected:\n";
    report += "- Memory dumps: 3 files\n";
    report += "- Network captures: 12 GB\n";
    report += "- Registry exports: 5 systems\n\n";
    report += "Key Findings:\n";
    report += "- Process injection detected in explorer.exe\n";
    report += "- Suspicious network connections to C2 servers\n";
    report += "- Persistence mechanisms in registry\n\n";
    return report;
}

QString ReportGenerator::generateExecutiveReport() {
    QString report;
    report += "EXECUTIVE SECURITY DASHBOARD\n";
    report += "============================\n\n";
    report += "Security Posture: GOOD\n";
    report += "Risk Level: MEDIUM\n";
    report += "Incidents This Month: 12\n";
    report += "Mean Time to Detection: 4.2 hours\n";
    report += "Mean Time to Response: 1.8 hours\n\n";
    report += "Key Metrics:\n";
    report += "- 99.7% uptime for security systems\n";
    report += "- 847 threats blocked automatically\n";
    report += "- 23 security awareness training sessions completed\n\n";
    return report;
}